version: '3.8'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"